### ISSUE TITLE
Another Feature Idea: Custom Colors Pie Chart

### ISSUE THREAD

**Issue by Minus10Celcius** [drbap/dashboard-navigator-for-obsidian#2]
Maybe you could use your plugin-settings to change the default colors?

Maybe in the Navigator area, we can change what shows in there? I personally don't need size, you could maybe incorporate properties and maybe see/change what properties are shown?

**Comment by drbap** [comment]
Thanks for the feedback! I appreciate you taking the time to share your ideas. Customization options are definitely on my to-do list, including the pie chart colors. I'm thinking about adding more color customization to the file icons as well. Additionally, I plan on offering the option to choose which information (columns) appears in the Navigator.

I'll have to think more about the properties suggestion. Incorporating properties seems like a great idea, but I'll have to test whether it will slow down the plugin. One of the goals is to keep it as fast and easy to use as possible.

I'll be sure to consider these features as I work on future updates. So if you have any other suggestions, please let me know.

All the best

**Comment by drbap** [comment]
Please check **plugin version 2.0.0**. Let me know if it is working well for you. Custom colors for piechart (you can also select colored files to show colored files -> dashboard and navigator views)

**New features**: 
- Hotkeys **open dashboard** and **open navigator**.
- **Excluded file extensions** functionality.
- **Excluded folders** functionality.
- Select **custom colors** -> files and piechart (all available file categories).
- **Colored files** in dashboard and navigator views (toggle).

All the best

**Comment by drbap** [comment]
You can hide specific columns in version 3.0.0. I hope you enjoy

All the best

**Comment by Minus10Celcius** [comment]
yippee!!

**Comment by drbap** [comment]
Please check plugin version 4.0.0. You can search for all frontmatter metadata (properties/aliases) -> new frontmatter column. Please check the changelong to know more about the new features. Some search adjustments too (date filter, quoted search).

I hope you enjoy

All the best
