### ISSUE TITLE
Feature idea: Excluded folders

### ISSUE THREAD

**Issue by oldjove** [drbap/dashboard-navigator-for-obsidian#3]
Hi! Wow, what a great plugin. Love it.

In the spirit of making a good thing better, I would find it helpful to be able to exclude certain folders from the dashboard view (e.g. I have various Zotero .bib files that I really don't need to see in the interface).

That's it, that's the request. ;)

**Comment by oldjove** [comment]
Great!

**Comment by drbap** [comment]
Please check **plugin version 2.0.0**. Let me know if it is working well for you. Excluded folders and file extensions available.

**New features**: 
- Hotkeys **open dashboard** and **open navigator**.
- **Excluded file extensions** functionality.
- **Excluded folders** functionality.
- Select **custom colors** -> files and piechart (all available file categories).
- **Colored files** in dashboard and navigator views (toggle).

All the best

**Comment by oldjove** [comment]
Hi,

Thanks for the updates. The excluded folders and file extensions seem to work well!

Best,
Jovan

**Comment by drbap** [comment]
Hi,

I'm glad to hear that the excluded folders and file extensions are working as expected! If you have any other questions or suggestions, please don't hesitate to reach out.

All the best
