### ISSUE TITLE
Ribbon and command palette commands

### ISSUE THREAD

**Issue by oldjove** [drbap/dashboard-navigator-for-obsidian#4]
One thing that's confusing me a little about the plugin is the open commands. In the ribbon I see "Open Dashboard Navigator", which opens the dashboard. Fair enough. In the command palette, on the other hand, there is one command: "Dashboard Navigator: Open". This opens the navigator interface.

Two things here: 

1. I would like to be able to do both things from the command palette (or rather, set hotkeys): open the dashboard and open the navigator. Is it possible to add a command to allow this? 
2. It would be helpful if the two commands had less similar names, because at the moment it's confusing. I'd suggest: "Dashboard Navigator: Open Dashboard" and "Dashboard Navigator: Open Navigator".

Possibly you might even want to think about whether it's better to rename the "navigator", because at the moment having the plugin called "Dashboard Navigator" but also having "navigator" as a sub-function creates a certain ambiguity (at least in my mind). Maybe "browser" or "file browser" would work?

Anyway, just some thoughts. I really like your plugin and will certainly use it no matter what.

**Comment by drbap** [comment]
Thanks for your feedback. Appreciated.

The suggestion to implement shortcuts/command palette options to trigger **Dashboard view** and other for **Navigator view** is useful, and it was added to the list of things to implement in future updates.
- "Dashboard navigator: Open dashboard".
- "Dashboard navigator: Open navigator".

I think these changes can improve the user experience without altering the plugin's name. I don't intend to change its name. The name "Dashboard Navigator" (or "Dashboard navigator" using sentence case) accurately reflects the plugin's dual functionality: providing a dashboard overview of your vault while also offering navigation tools. The dashboard is also a navigator. You can click or right-click on the links and navigate to the recent files and also access filtered results -> Navigator view, for example clicking on Images button will open all images in Navigator. You can use the search feature on Dashboard view, don't have to switch to Navigator view.

I'm committed to making Dashboard navigator as user-friendly and fast as possible, and user feedback is essential in achieving that goal.

Thanks again for taking the time to show your opinion and feedback.

Stay tuned for the next updates.

All the best

**Comment by drbap** [comment]
Please check **plugin version 2.0.0**. Let me know if it is working well for you.

**New features**: 
- Hotkeys **open dashboard** and **open navigator**.
- **Excluded file extensions** functionality.
- **Excluded folders** functionality.
- Select **custom colors** -> files and piechart (all available file categories).
- **Colored files** in dashboard and navigator views (toggle).

All the best

**Comment by drbap** [comment]
Thank you for your valuable feedback. You're absolutely right that the "**Dashboard navigator: Open**" command might seem redundant given the "**Open dashboard**" and "**Open navigator**" options.

To ensure a seamless experience for all users, I've decided to maintain this command for backward compatibility. Many users may have already customized their workflows around it, including assigning a hotkey.

Additionally, keeping this command aligns with the behavior of the **ribbon action**, which opens the default view selected by the user (the default view is the **Dashboard** - open dashboard view). This consistency helps prevent confusion and ensures a smooth transition for users familiar with the existing functionality.

All the best

**Comment by drbap** [comment]
Thanks again for the suggestion. If you have other suggestion, just let me know.

All the best

**Comment by drbap** [comment]
**"Dashboard navigator: Open"** was removed -> **plugin version 3.0.0**. You can use the specific shortcuts commands to trigger navigator or dashboard views.

All the best
