### ISSUE TITLE
Jpeg vs jpg

### ISSUE THREAD

**Issue by mudnug** [drbap/dashboard-navigator-for-obsidian#7]
**Is your feature request related to a problem? Please describe.**
Could jpeg be classified as Image instead of Other

**Describe the solution you'd like**
Could jpeg be classified as Image instead of Other

Dashboard is showing jpeg images as 'other'
![image](https://github.com/user-attachments/assets/5f10424a-44e6-4690-9a28-66219741a621)

**Comment by drbap** [comment]
Thanks for stopping by and the comment. Sure, I will add it to the list of features to implement on the next update.

Stay tuned.

All the best

**Comment by mudnug** [comment]
const extensions: Record<string, TFile[]> = {
    'md': arrNotes,

    // Image formats
    'png': arrImages,
    'jpg': arrImages,
    'jpeg': arrImages,
    'webp': arrImages,
    'ico': arrImages,
    'bmp': arrImages,
    'gif': arrImages,
    'tif': arrImages,
    'tiff': arrImages,
    'raw': arrImages,
    'svg': arrImages,
    'psd': arrImages,

    // Audio formats
    'mp3': arrAudios,
    'wav': arrAudios,
    'ogg': arrAudios,
    'webm': arrAudios,
    'aac': arrAudios,
    'flac': arrAudios,
    'm4a': arrAudios,

    // Video formats
    'mp4': arrVideos,
    'avi': arrVideos,
    'mov': arrVideos,
    'wmv': arrVideos,
    'flv': arrVideos,
    'mkv': arrVideos,

    // Document formats
    'pdf': arrPDFs,

    // Other
    'canvas': arrCanvas
}

**Comment by drbap** [comment]
Please check **plugin version 2.1.0**. Let me know if it is working well for you. The **.jpeg** files should be listed as images now (not Other).

- Added image file extensions -> category of images: jpeg, svg, avif.
- Added audio file extensions -> category of audios: aac, flac, aiff, m4a.
- Added video file extensions -> category of videos: mov, mkv.

If it is working ok, you can close this issue. Thanks for the suggestions.

All the best

**Comment by mudnug** [comment]
Yes, I tested with jpeg files with the latest release and the update is working as desired!
