### ISSUE TITLE
Please add "file extensions" column in navigator view. Thanks! （Looking forward to adding more attributes, such as aliases)

### ISSUE THREAD

**Issue by nanjingman** [drbap/dashboard-navigator-for-obsidian#9]
Please add "file extensions" column in navigator view. Thanks! （Looking forward to adding more attributes, such as aliases)

**Comment by drbap** [comment]
Thank you for your valuable feedback. I appreciate you taking the time to share your thoughts. The suggestion to add a "file extensions" column to the navigator view is a good idea. I'll consider this enhancement for future updates.

As for adding more attributes like aliases, I'm continuously working on improving the tool's functionality and user experience. I'll keep your suggestion in mind as I work on potential future features.

**Comment by nanjingman** [comment]
Thanks!

**Comment by drbap** [comment]
The **Extension** column will be available in the next update. Thanks for the suggestion. Stay tuned.

**Comment by drbap** [comment]
Please check **plugin version 3.1.0**. Let me know if it is working well. You can check the changelog for the other new features.

All the best

**Comment by nanjingman** [comment]
Thank you for your efficient work! Could you please add a title line filtering function similar to Excel?
谢谢您的高效工作！能再请您加上类似于Excel的标题行筛选功能吗？
![image](https://github.com/user-attachments/assets/2bf91efe-5ed2-4ddb-8709-38ebb9be0a0a)

**Comment by nanjingman** [comment]
Haode. Thanks!

**Comment by drbap** [comment]
Please check **plugin version 4.0.0**. You search for aliases and all frontmatter metadata (check changelog to know the new features).

I hope you enjoy.

All the best

**Comment by nanjingman** [comment]
Thanks! For me, it would be perfect if the first alias could be listed separately in columns.
